import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navBar";

import { UserProvider } from '@auth0/nextjs-auth0/client';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Unifyte",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <div className="w-screen h-screen">
            <div className="h-20">
              <NavBar />
            </div>
            <div className="h-[calc(100vh-5rem)]">{children}</div>
          </div>  
        </body>
      </UserProvider>
    </html>
  );
}
